_target_: src.utils.hydra_sklearn_pipeline.make_pipeline

#StepName:
#    _target_: <class to initiating the step>
#    param1: <step's first parameter>
#    param2: <step's second parameter, etc.>

steps_config: # use yaml list syntax to preserve to order
  - CountVectorizer:
      _target_: sklearn.feature_extraction.text.CountVectorizer
      lowercase: True
      stop_words: 'english'
      max_df: 0.5
      min_df: 10

  - Normalizer:
      _target_: sklearn.preprocessing.Normalizer
      copy: False