#data: "data/titles.csv"

mlflow:
  experiment_name: sc

defaults:
  - model: spectral_nn
  - vectorizer: count

GridSearchCV:
#  scoring: sklearn.metrics.silhouette_score #[sklearn.metrics.silhouette_score, sklearn.metrics.calinski_harabasz_score, sklearn.metrics.davies_bouldin_score]
#  cv: 5
  n_jobs: 4

metrics:
  score: metrics.silhouette_score
  average: macro